apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -two

commonLabels:
  app.kubernetes.io/name: two

resources:
  - ../base

patches:
  - path: rollout.patch.yaml
    target:
      kind: Rollout
