apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: nginxinc-playground.api.argoproj.io
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-stable
            port:
              name: http
