apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
 - name: ingress-nginx
   repo: https://kubernetes.github.io/ingress-nginx
   version: 4.7.1
   releaseName: ingress-nginx
   namespace: ingress-nginx
   valuesFile: values.yaml
