apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: backend

images:
  - name: image_name
    newName: argoproj/rollouts-demo

resources:
- service.yaml
- rollout.yaml
