apiVersion: v1
kind: Service
metadata:
  name: stable
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: preview
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: backend
