apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: ns-istio-injection.yaml
    target:
      kind: Namespace
      name: nginx-ingress
  - path: deploy-istio-annotations.yaml
    target:
      kind: Deployment
      name: nginx-ingress
