apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - telemetry.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.19/samples/addons/kiali.yaml

helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.19.0
    releaseName: istio-base
    namespace: istio-system
    includeCRDs: true
    valuesInline:
      revision: "v1-19-0" # this appends `istio.io/rev` label
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.19.0
    releaseName: istiod
    namespace: istio-system
    includeCRDs: true
    valuesInline:
      revision: "v1-19-0" # this appends `istio.io/rev` label
  # - name: gateway
  #   repo: https://istio-release.storage.googleapis.com/charts
  #   version: 1.19.0
  #   releaseName: istio-ingressgateway
  #   namespace: istio-ingress
  #   includeCRDs: true
