apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kiali-server
    repo: https://kiali.org/helm-charts
    version: 1.74.0
    releaseName: kiali-server
    namespace: istio-system
    valuesInline:
      auth:
        strategy: "anonymous"
