apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playground

resources:
  - ./canary

images:
  - name: ybelval/rollouts-demo
    newName: argoproj/rollouts-demo
    newTag: blue

patches:
  - path: rollout.patch.yaml
    target:
      kind: Rollout
