apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playground

resources:
  - https://raw.githubusercontent.com/yohanb/argo-rollouts-examples/main/apps/prototype/canary/namespace.yaml
  - https://raw.githubusercontent.com/yohanb/argo-rollouts-examples/main/apps/prototype/canary/service.yaml
  - https://raw.githubusercontent.com/yohanb/argo-rollouts-examples/main/apps/prototype/canary/rollout.yaml
  - https://raw.githubusercontent.com/yohanb/argo-rollouts-examples/main/apps/prototype/canary/istio-virtual-service.yaml
  - https://raw.githubusercontent.com/yohanb/argo-rollouts-examples/main/apps/prototype/canary/nginx-virtual-server.yaml

images:
  - name: ybelval/rollouts-demo
    newName: argoproj/rollouts-demo
    newTag: blue

patches:
  - path: rollout.patch.yaml
    target:
      kind: Rollout
