apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -complex

resources:
  - ingress.yaml
  - gatekeeper
  - one
  - two
  - three
  - job.yaml

images:
  - name: argoproj/rollouts-demo
    newTag: green
