apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playground

resources:
- rollout.yaml
- service.yaml

# override image tag from blue to gree
images:
  - name: argoproj/rollouts-demo
    newTag: green

components:
  - with-istio
  - fast-rollback-with-istio

nameSuffix: -simple
