apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playground

resources:
# - ingress.yaml
- service.yaml
- rollout.yaml
- virtualservice.yaml

# override image tag from blue to gree
images:
  - name: argoproj/rollouts-demo
    newTag: blue
