apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playground

resources:
- istio/gateway.yaml
- istio/virtual-service.yaml
- nginx-ingress/virtual-server.yaml
- rollout.yaml
- service.yaml

# override image tag from blue to gree
images:
  - name: argoproj/rollouts-demo
    newTag: green
