apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -one

commonLabels:
  app.kubernetes.io/name: one

resources:
  - ../base

patches:
  - path: rollout.patch.yaml
    target:
      kind: Rollout
